name: Publish to crates.io

on:
    push:
      branches:
        - main

env: 
  CARGO_TERM_COLOR: always

jobs:
    publish:
        name: Rust project - latest
        runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable
        steps:
            - uses: actions/checkout@v4
            - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - run: cargo publish --verbose
